apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: danclien-com
  namespace: danclien-com
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: danclien-com
    spec:
      containers:
      - image: danclien/danclien-com
        imagePullPolicy: Always
        name: danclien-com
        ports:
        - containerPort: 8080
